const series = [null,
  {
    "The most unusual item": [4,1,2,3,5],
    "Eat as much watermelon as possible": [2,3,1,5,4],
    "Paint a horse while riding a horse": [5,3,1,4,2],
    "Empty the bathtub": [4,3,2,5,1],
    "Pop up a tent and pop on a onesie": [4,3,1,2,5],
    "The most impressive item": [4,2,3,1,5],
    "High-five a 55-year-old": [2,5,4,1,3],
    "Identify the contents of the pies": [1,2,4,3,5],
    "Do something that will look impressive in reverse": [1,4,5,5,3],
    "Unshackle yourself and sprint one metre": [1,3,5,4,2],
    "The most meaningful item": [4,2,1,5,3],
    "Throw a teabag into a mug": [4,0,2,3,5],
    "Draw an image using a GPS device": [2,5,1,4,3],
    "Buy a gift for the Taskmaster": [3,5,4,2,1],
    "Get an egg as high as possible": [0,5,0,4,0],
    "Stand up after 100 seconds": [2,5,1,4,4],
    "The most beautiful item": [3,4,2,1,5],
    "Make a block of ice disappear": [4,5,3,2,1],
    "Score 11 points": [1,2,2,2,1],
    "Fill an eggcup with tears": [5,3,1,4,1],
    "Memorise an Australian Rules Football team": [1,1,1,1,1],
    "The most valuable item": [4,5,1,3,2],
    "Move the boulder as far as possible": [4,5,1,2,3],
    "Grow the longest nail": [3,5,2,4,1],
    "Make a bed while holding hands": [2,0,0,0,2],
    "Make a Swedish person blush": [3,1,5,4,2],
    "Inflate the largest balloon while blindfolded": [4,2,5,3,0],
    "The most satisfying item": [2,4,1,3,5],
    "Play mini golf with eggs": [4,2,5,1,3],
    "Stage a realistic home movie blooper": [2,0,0,0,2],
    "Make an alphabet meal": [5,1,1,4,3],
    "Separate the blue sweets": [3,2,1,4,5]
  },
  {
    "The most important document": [4,5,2,3,2],
    "Place the exercise balls on the yoga mat": [1,2,4,3,5],
    "Get the potato into the hole": [2,0,5,3,4],
    "Find out about the Swedish person": [2,1,3,5,4],
    "Pack a suitcase": [0,0,4,3,5],
    "The trendiest item of clothing": [5,2,3,4,1],
    "Quickly eat an egg": [4,2,3,0,5],
    "Create a nursery rhyme video": [5,2,5,4,3],
    "A photo of an object that looks like you": [1,2,4,3,5],
    "Order a pizza without using certain words": [3,5,5,4,1],
    "Put potatoes in a basket": [0,0,5,4,0],
    "The best dinner party guest": [3,5,1,4,2],
    "Impress the Mayor": [2,3,1,5,4],
    "Make an unexpected silhouette": [1,3,5,2,4],
    "Buy a gift for the Taskmaster": [3,2,1,4,5],
    "See no potato, hear no potato, speak no potato": [0,0,5,0,5],
    "Throw rabbits into a hat": [12,12,4,15,7],
    "The coolest blue item": [3,4,5,2,1],
    "Rescue Patatas from the tree": [4,3,2,5,0],
    "Conceal a pineapple on your person": [2,1,5,4,3],
    "Set a task / Guess who set the tasks": [0,0,4,0,0],
    "Construct something for the Taskmaster": [4,4,1,4,1],
    "Build the tallest tower using potato products": [5,0,0,0,0],
    "The best piece of memorabilia": [2,1,3,4,5],
    "Move items across a stream": [0,5,0,3,4],
    "Create a stop-motion film starring a potato": [2,2,3,2,3],
    "Build a bridge for the potato": [4,3,5,1,2],
    "Put on gloves, eat a banana, put on a tie, and clap": [4,0,2,3,5]
  },
  {
    "The most flamboyant clock": [4,3,1,2,5],
    "Reach the microwave in the fewest steps": [4,2,0,5,3],
    "Propel a pea along a red carpet": [5,0,2,4,3],
    "Make the best snowman": [3,5,1,2,4],
    "Balance swedes on a Swede": [5,3,4,2,1],
    "The heaviest shoebox-sized item": [3,5,2,4,1],
    "Surprise Alex": [4,3,1,5,2],
    "Release Alex": [0,0,0,5,5],
    "An upside-down condiment self-portrait": [5,3,2,2,4],
    "Burst all of the balloons": [1,3,4,5,2],
    "Unravel the tape": [5,3,4,0,2],
    "The best battery-operated item": [2,1,4,5,3],
    "Fill an eggcup with sweat": [0,3,5,2,4],
    "Make the best domino rally": [1,4,5,3,1],
    "Buy a gift for the Taskmaster": [3,5,2,4,1],
    "Create the best flag meal": [2,5,4,1,3],
    "Anchor balloons using bread": [1,3,2,4,5],
    "The shiniest thing": [1,3,5,2,4],
    "Spread your clothes far and wide": [5,3,1,4,2],
    "Find out the lying old man’s occupation": [5,4,1,2,3],
    "Create an impressive special effect": [3,3,3,2,2],
    "Cover yourself in sticky notes": [2,4,1,5,3],
    "The most handsome relative": [4,5,1,3,1],
    "Move water from one bucket to another": [5,0,3,4,3],
    "Play charades across a river": [5,5,5,0,0],
    "Create an impressive time-lapse or slow motion film": [2,3,3,5,5],
    "The lowest unique number of doughnuts": [0,0,0,5,0]
  },
  {
    "The most interesting vegetable autograph": [1,2,3,4,5],
    "Beautifully destroy a cake": [1,5,2,3,4],
    "Draw a blind portrait": [2,4,3,3,5],
    "Fell all the ducks": [5,3,4,1,2],
    "Make the most fruit juice": [4,3,1,5,2],
    "The most boastful item": [1,2,4,3,5],
    "Keep the basketball on the treadmill": [5,2,4,3,1],
    "Paint a portrait of the Taskmaster without touching the red mat": [0,4,2,3,5],
    "Get the flour onto the target": [5,0,0,5,0],
    "Put an egg in an egg cup without touching either": [2,3,5,1,4],
    "Make the longest balloon chain": [4,2,3,5,3],
    "The best subscription": [1,3,4,2,5],
    "Camouflage yourself": [4,4,2,1,5],
    "Make a Taskmaster movie trailer": [3,2,2,3,2],
    "Persuade three animals to stand on the mat": [3,5,4,1,4],
    "Transfer water from one fishbowl to another": [4,0,0,-4,3],
    "Musical words": [0,5,0,0,0],
    "The most surprising picture of yourself": [1,4,5,3,2],
    "Make the highest splash": [2,3,1,4,5],
    "Ringtone choreography": [1,2,3,5,5],
    "Make the best toilet paper celebrity portrait": [3,4,2,2,5],
    "Do something incredible with a pommel horse": [5,3,1,5,3],
    "Make the tallest tube tower": [5,3,3,5,3],
    "The cutest thing": [1,4,5,2,3],
    "Slide as far as possible": [4,2,1,5,3],
    "Don the diving gear while maintaining eye contact and small talk": [3,5,5,2,1],
    "Do incompatible things with the bathtub": [5,0,0,5,0],
    "Throw something into something": [3,2,1,5,4],
    "Make the longest continuous noise": [5,5,3,2,1],
    "The best sheep-related item": [2,3,5,1,3],
    "Pass a camel through a small gap": [4,2,3,5,1],
    "Score a goal with a shopping bag": [5,3,3,4,1],
    "Identify the contents of the sleeping bag": [0,5,5,2,5],
    "Prepare the items / Lift all the items in one hand": [2,1,3,4,5],
    "The best chair": [5,2,3,1,4],
    "Cross the bunting to give Alex his lunch": [4,3,1,2,5],
    "Hide from Alex": [3,3,5,4,1],
    "Wheelie bin obstacle course": [2,3,3,2,3],
    "Invent a new handshake": [3,5,3,3,4],
    "Make the biggest and best banana": [3,4,5,1,2],
    "The most cash": [1,4,5,2,3],
    "Create an exotic sandwich": [1,4,3,2,5],
    "Eat your exotic sandwich": [5,2,3,5,2],
    "Strike an item the farthest": [4,3,1,2,5],
    "Do something surprising with a duck": [2,3,1,5,4],
    "Draw the median duck": [0,0,0,5,1]
  },
  {
    "The most excellent noise": [3,2,5,1,4],
    "Give Alex a special cuddle": [3,5,2,2,4],
    "Get Alex to dry land": [3,2,1,5,4],
    "Score a basket without your hands": [3,5,4,2,0],
    "Get some fruit into the bowl": [1,4,5,3,2],
    "The hippest headwear": [3,4,2,1,5],
    "Make a coconut-flinging machine": [2,5,2,3,4],
    "Paint a rainbow in the dark": [5,1,3,2,4],
    "Slice bread using something from the caravan": [0,0,4,5,0],
    "Create the greatest splat": [2,2,3,3,2],
    "Paint your own canvas": [5,4,5,5,5],
    "The proudest item": [3,5,2,1,4],
    "Retrieve the table tennis ball from the tube": [0,5,3,2,4],
    "Make a coconut businessman": [3,1,4,5,2],
    "Eat one item, balance one item, throw one item": [2,4,3,0,5],
    "Word table tennis": [5,2,3,4,1],
    "The most extraordinary souvenir": [5,1,2,4,3],
    "Make marmite": [3,5,4,0,2],
    "Do something remarkable synchronised": [3,3,2,2,3],
    "Blow up a balloon to the size of a cucumber": [3,4,5,1,2],
    "Spot the difference": [5,2,3,3,2],
    "Sneeze the fastest": [0,5,4,0,0],
    "Greg says...": [5,1,4,2,3],
    "The most high-octane item": [3,4,1,2,5],
    "Put the largest thing inside a balloon": [5,0,4,0,0],
    "Create a remarkable water cooler moment": [2,3,1,4,5],
    "Build a can tower & greet Alex from different countries": [1,5,5,3,2],
    "Identify the Finns": [4,2,5,4,2],
    "The best home-made item": [4,5,1,3,2],
    "Balance Alex on a see-saw": [3,2,1,5,4],
    "Record the most incredible PoV footage": [4,4,4,1,5],
    "Light a candle using a cupcake": [1,5,4,2,3],
    "Make yourself monotone": [5,2,3,1,4],
    "The most surprisingly expensive item": [3,3,5,1,4],
    "Travel blindfolded for three minutes and retrace your steps": [4,5,2,1,3],
    "Coconut bobsleigh": [5,0,3,4,0],
    "Vote for who should receive five points": [0,0,-2,-2,5],
    "Make a funny flick book": [3,5,3,5,3],
    "Zipwire items to the Taskmaster": [2,5,4,3,1],
    "The most awkward item to take home": [2,1,5,4,3],
    "Transport a coconut as far as possible": [3,4,0,2,5],
    "Create the best graph": [3,4,3,5,3],
    "Write and perform a song about a stranger": [2,2,3,3,2],
    "Throw an egg through a basketball hoop": [0,5,0,0,4]
  },
  {
    "The best liquid": [4,1,3,1,5],
    "Perform the best wheelbarrow stunt": [5,1,3,4,2],
    "Make the tallest lemon tower": [4,1,3,5,2],
    "Return to the house wearing a hat": [5,1,3,4,2],
    "Sort the objects by size using your feet": [0,4,5,4,0],
    "The best non-living hairy thing": [2,1,4,2,5],
    "Get the highest darts score": [2,3,5,1,4],
    "Keep Alex dry": [4,1,1,4,1],
    "Take a picture of people holding eggs": [2,3,5,4,1],
    "Take the wind-up man on an adventure": [3,5,4,3,3],
    "Conceal grapes in your mouth or hand": [0,0,0,0,0],
    "The most magnificent day trip": [1,2,4,3,5],
    "Write a grown-up bedtime story": [1,3,5,3,2],
    "Make something spin for the longest": [1,4,5,2,3],
    "Identify the baby food flavours": [2,6,4,3,1],
    "Catch the most socks": [1,4,4,5,4],
    "The most thought-provoking thing": [3,1,2,5,4],
    "Do something manly with a cardboard box": [4,4,5,4,4],
    "Have the most fun in 3 minutes": [2,3,3,2,3],
    "Exactly recreate your 3 minutes of fun": [5,5,5,5,5],
    "Make the best squirty cream art": [4,1,5,3,2],
    "Remove the banknote from under the glass": [0,4,0,5,3],
    "Shake hands with the Taskmaster without revealing your identity": [5,0,0,0,0],
    "The sturdiest thing": [4,1,5,3,2],
    "Work out the length of a piece of string": [2,4,1,3,5],
    "Remove the tablecloth from underneath the eggs": [5,5,5,5,5],
    "Identify the link and do it 100 times": [3,5,5,3,5],
    "Pull off an elaborate snooker trick shot": [1,2,4,3,5],
    "Throw eggs onto a shelf": [1,2,5,4,4],
    "The best invention": [1,1,3,1,5],
    "Make the best snow globe": [3,1,4,5,3],
    "Knock over the ducks without leaving the carpet": [0,5,5,0,5],
    "Make the best announcement": [2,5,2,1,4],
    "Make a parachute for a wooden spoon": [4,1,5,2,3],
    "Predict how many words you can list for a category": [5,4,1,3,3],
    "The scariest thing from the kitchen": [2,4,3,5,1],
    "Knock the bails off the stumps": [0,0,0,5,4],
    "Draw the contents of the box": [4,1,5,2,4],
    "List and then mime obscure animals": [3,2,2,3,2],
    "Make and eat a pancake with objects tucked into your sweatband": [2,3,5,5,5],
    "Roll eggs to the centre of the target": [3,5,2,1,4],
    "The most interesting footwear": [1,5,3,2,4],
    "Put something surprising inside a chocolate egg": [5,3,3,3,4],
    "Find out what you have in common with a stranger": [2,5,3,4,2],
    "Make a join-the-dots image using stiletto heels": [2,1,4,3,5],
    "Stick plasters to the correct body parts": [3,2,4,5,1],
    "The most pleasing cat-sized thing": [3,2,1,4,5],
    "Make the biggest bubble and burst it with your nose": [5,3,4,1,2],
    "Perform a number from the Taskmaster musical": [3,2,2,3,2],
    "Make an outfit with stationery / Guess what pun Tim will make": [0,0,0,0,2],
    "Make a plastic bag as heavy as possible": [3,4,5,2,1],
    "Hold the most points above the ground": [4,1,2,5,4],
    "The least appropriate wedding accessory": [3,5,1,4,2],
    "Knock over the fewest bowling pins": [3,3,4,5,1],
    "Blow out a candle from a distance": [3,5,0,2,4],
    "Declare your love for the Taskmaster": [2,5,5,1,3],
    "Pick numbers higher and lower than the people next to you": [5,4,0,0,3]
  },
  {
    "The thing most people want to touch": [2,1,2,5,4],
    "Make the best quick-change outfit": [2,4,5,1,3],
    "Build the tallest cardboard box tower": [1,3,4,2,5],
    "Work out the perimeter of the caravan in beans": [4,3,5,1,2],
    "Make the most exotic fruit hat": [2,3,4,4,5],
    "The boldest belt": [1,2,3,4,5],
    "Write a ten word story while running": [5,4,3,2,1],
    "Paint a blindfolded still life": [3,2,2,3,3],
    "Predict what another contestant will do with an object": [5,10,5,5,5],
    "Draw the biggest and best circle": [1,3,5,2,4],
    "Build a tower of cans within a hoop": [1,2,5,3,4],
    "The best thing from the 90s": [4,0,5,3,0],
    "Raise Alex’s heart rate": [4,5,3,1,2],
    "Make the best noise": [2,4,3,5,1],
    "Get the ball into the hole by striking it": [3,1,2,4,5],
    "Silently mouth a ten word fact to Greg": [5,5,4,2,1],
    "The most confusing thing": [1,5,2,4,3],
    "Work out what the switch does": [5,2,4,3,1],
    "Change your appearance in a lift": [1,4,3,2,5],
    "Make the scales read exactly 31.770kg": [5,1,3,2,4],
    "Get dressed while wearing handcuffs": [5,4,4,1,4],
    "The worst gift from a relative": [2,5,3,1,4],
    "Spectacularly deliver the task to Alex": [5,3,1,2,4],
    "Make the most white circles on the target": [5,5,5,0,5],
    "Cheer up the traffic warden": [5,5,1,3,2],
    "Make yourselves appear as large or small as possible": [3,2,2,3,3],
    "Place objects on the hanger without it falling": [0,5,5,0,0],
    "The best key": [1,4,5,2,3],
    "Put 50 different things in the bin": [5,2,4,2,3],
    "Make a portrait of the Taskmaster using your 50 items": [5,2,3,1,4],
    "Make a soap opera cliffhanger": [3,2,2,3,3],
    "Place 10 pairs of glasses into the smallest box": [2,4,3,5,0],
    "Get your inflatable ring as high as possible": [3,2,0,4,5],
    "The most exciting thing beginning with 'G'": [2,1,1,1,2],
    "Throw something into the bin behind the fence": [1,3,2,4,5],
    "Don’t blink": [3,4,1,2,5],
    "Build an extension to the Taskmaster house": [2,4,4,1,1],
    "Make the best Christmas cracker": [3,3,3,5,3],
    "Beat on the drum after exactly 9.58 seconds": [4,3,3,2,5],
    "The creepiest thing": [4,2,5,1,5],
    "Poke something unexpected through the hole": [2,4,2,2,5],
    "Follow the clues and then do what they spell": [5,4,3,2,1],
    "Compose a 30 second piece of music": [4,5,3,2,4],
    "Bob, pat, kneel, stew, or wane": [1,4,3,2,5],
    "The most surprisingly beautiful thing": [3,4,2,5,1],
    "Put the largest numeric value of money in the floating bowl": [0,0,5,0,0],
    "Take a photo of yourself in a fez / Improve your hula-hooping": [2,3,2,1,1],
    "Find the satsuma in a sock": [3,2,4,0,4],
    "Complete a 24-shot rally": [1,5,5,1,1],
    "Draw a happy horse upside-down": [5,4,3,4,2],
    "The most magnificent stationery": [3,2,5,4,1],
    "Put on overalls and lie on the ground when the siren sounds": [2,3,1,5,4],
    "Find the hard-boiled egg": [5,0,0,0,0],
    "Recreate a classic video game": [5,3,2,3,4],
    "Tie yourself up as securely as possible": [4,3,2,1,5],
    "Sausage or finger?": [0,0,5,0,0]
  },
  {
    "The most powerful smell": [2,1,5,3,3],
    "Find the baby monitor receiver": [5,3,2,1,4],
    "Make and be seduced by a ventriloquist dummy": [5,1,4,4,4],
    "Sneak up on Alex": [4,5,4,1,2],
    "Collect the most doughnuts in your bucket": [4,2,5,1,3],
    "The best pair of things": [4,1,3,4,5],
    "Make a moustache from something unexpected": [2,3,4,5,1],
    "Transfer the rice to the bottle": [3,5,4,1,2],
    "Convey an object using only facial expressions, noises, adjectives & verbs": [2,3,2,2,3],
    "Travel the furthest while making a continuous noise": [1,5,4,2,3],
    "Name a bird, eat a grape, name a contestant": [1,3,4,5,2],
    "The best burstable thing": [3,2,1,4,5],
    "Build the best volcano": [2,5,5,3,2],
    "Work out what Alex is wearing": [3,0,4,2,5],
    "Do the worst thing and make the best apology": [4,2,5,1,3],
    "Get into two sleeping bags and complete other actions": [5,1,4,1,1],
    "The best present for a doctor": [1,4,3,1,5],
    "Get the toilet paper through the toilet seat": [5,4,4,1,2],
    "Make the best thing to entertain a toddler": [4,4,3,5,5],
    "Get the most weight into a hammock": [0,3,0,0,3],
    "Throw a frying pan into a hoop": [0,0,5,4,0],
    "The best face": [5,1,2,4,3],
    "Move the sand from one bucket to another": [0,4,5,2,3],
    "Make a realistic injury using food": [4,4,4,1,5],
    "Play long-distance catch with a beach ball": [3,2,3,4,2],
    "Herd the ping pong balls into a pen": [5,4,4,1,2],
    "Recreate the scene you parade past": [4,5,2,2,2],
    "The best see-through item": [1,4,1,1,1],
    "Conceal yourself inside a phone box": [5,2,4,1,2],
    "Design an iconic album cover": [2,4,2,2,4],
    "Recall the order of the deck of cards": [2,4,0,5,3],
    "Score a goal from the greatest distance": [0,0,0,0,5],
    "Roll a toilet roll, and retrieve your shoe": [0,0,5,0,0],
    "The best slippery thing": [3,4,5,4,2],
    "Find the apples": [0,5,4,3,0],
    "Work out the crisp flavours": [4,5,2,3,2],
    "Do something powerful with your little finger": [3,5,2,3,2],
    "Answer the questions, pull the strings; do not release the green egg": [0,5,0,0,5],
    "The nicest thing to hold": [3,4,2,5,3],
    "Make a portrait of a former contestant using sand and one tool": [5,2,2,4,1],
    "Catch the tennis balls": [5,0,5,5,0],
    "Move the beach ball across the finish line using only water": [5,1,3,2,4],
    "Complete the five-syllable words": [0,0,0,5,0],
    "The best form of protection": [4,3,5,4,3],
    "Get a ball into a bin with the most bounces": [3,1,5,2,4],
    "Make a delicious dust meal": [5,4,1,3,2],
    "Make yourselves look like one person": [3,2,3,3,2],
    "Complete some tasks as one person": [1,4,1,1,4],
    "Stack plates and bowls on your head": [3,2,5,4,1],
    "The best thing that will change your life for the better": [5,4,3,3,2],
    "Erase the eraser": [5,4,4,4,2],
    "Make the most tremendous legs": [3,1,4,2,5],
    "Blindly drive a mobility scooter around a course": [5,3,1,2,4],
    "Hook a duck while wearing inversion goggles": [0,0,0,0,0]
  },
  {
    "The most stressful thing": [4,2,3,5,2],
    "Hide three aubergines from Alex": [1,5,2,3,4],
    "Arrange the lollies in rainbow order": [3,5,3,1,5],
    "Make the most dramatic entrance": [1,4,4,3,5],
    "Draw the second longest snake": [5,0,0,0,1],
    "The best bag": [1,2,3,4,5],
    "Identify which bin Alex is in": [4,5,0,0,0],
    "Draw a portrait of the Taskmaster across a flipchart": [1,3,4,5,3],
    "Say the word ‘demeaning’": [3,5,3,5,5],
    "Arrange the playdough balls / Do the correct things with the balls": [1,4,5,4,2],
    "The weirdest wooden thing": [5,3,1,4,2],
    "Surprise memory test": [4,3,1,5,2],
    "Build a robust statue of a delicate thing": [2,2,3,5,4],
    "Score a goal with a steamroller": [1,3,4,2,5],
    "Break something and put it back together": [2,1,5,3,4],
    "Fill a glass with water": [3,5,1,4,3],
    "The best thing to celebrate with on stage": [3,5,4,2,2],
    "Make the most striking water feature": [4,5,2,1,3],
    "Bring a classic board game to life": [3,3,3,3,3],
    "Fill a tray with things beginning with a letter you chose": [1,2,3,4,5],
    "Throw objects, but not too far": [1,1,4,1,5],
    "The best defunct thing": [5,2,3,4,1],
    "Lasso Alex": [1,2,5,3,4],
    "Make an accurate and inventive egg timer": [2,1,5,3,4],
    "Get to know a person who alternately tells the truth, lies, and brags": [2,4,3,4,4],
    "Build a tower behind you using a mirror and litter pickers": [2,5,3,2,5],
    "The thing you’d be most pleased to find in a field": [3,5,4,1,2],
    "Make a body part abnormally long": [1,3,5,3,4],
    "Push a watermelon up a slide using breadsticks": [0,5,0,1,0],
    "Serenade yourself": [2,5,5,3,5],
    "Slide drinks to the Taskmaster": [4,1,2,5,3],
    "The best thing taken from someone else’s house": [5,3,1,4,2],
    "Throw eggs into metal receptacles": [3,4,2,5,1],
    "Build the best Mount Rushmore": [5,4,3,5,4],
    "Find and put the gold rings on the stick": [1,5,3,5,3],
    "Horse or laminator?": [0,1,13,5,1],
    "The best thing from a shed": [2,4,5,1,3],
    "Throw something into a pedal bin": [1,5,4,3,2],
    "Write and perform lyrics for the Taskmaster theme tune": [2,4,1,3,5],
    "Supply a soundtrack for a film": [2,3,2,3,3],
    "Draw your own face on a face shield": [3,4,3,5,4],
    "The most desirable smooth thing": [5,4,4,4,4],
    "Subtly deliver a five word instruction to Alex": [5,2,4,3,2],
    "Inflate, tie, and pop the most balloons": [3,5,0,0,4],
    "Make a famous couple using knees and/or elbows": [3,3,1,5,2],
    "Communicate pictures by drawing on your team-mate’s back": [3,3,5,5,5],
    "The best thing that is very long and thin": [3,2,4,5,1],
    "Do the most preposterous thing with a chickpea": [2,4,1,3,5],
    "Make a cup of tea": [5,1,5,1,1],
    "Complete the seven tasks in any order": [0,5,0,0,0],
    "Select the shortest breadstick": [0,0,0,0,5]
  },
  {
    "The nicest thing to put in your mouth": [5,3,2,1,4],
    "Fell the coconut, then move the drinks": [0,0,0,0,0],
    "Make a large object vanish": [1,4,3,5,3],
    "Get the most eggs in the pan": [1,0,0,0,0],
    "Get the most balls of the same colour in your bucket using litter pickers": [4,3,1,2,5],
    "The best thing with loads of holes in it": [2,1,4,5,3],
    "Find the treasure / Make different, increasingly loud noises": [4,4,5,5,4],
    "Make a portrait of the Taskmaster and his toy using balloons, pegs, and clothing": [1,5,4,2,2],
    "Get all the exercise balls in the hoops while in a boat": [5,2,3,0,4],
    "Guess what is making the noises": [6,3,3,4,6],
    "The best thing that probably has a spring": [1,5,2,4,3],
    "Make the best upside-down film": [2,5,3,4,1],
    "Put the most spaghetti in a grapefruit": [5,3,1,4,2],
    "Catapult a shoe into a bathtub": [5,4,1,2,3],
    "Draw an object on a rotating canvas": [6,0,0,0,6],
    "The cheekiest food": [2,1,4,5,3],
    "Make the phone ring": [4,1,2,3,5],
    "Persuade the security guard to look in your bag": [5,5,0,0,0],
    "Drop a water balloon as far as possible without it bursting": [5,5,5,3,4],
    "Roll an edible sphere across a line as slowly as possible": [3,5,4,2,1],
    "The best pointy thing": [2,3,4,1,5],
    "Bag the heaviest thing from the greatest distance": [2,1,5,3,4],
    "Paint a howling wolf on a rotating teapot": [5,3,1,2,5],
    "Do something out of character with £20": [5,4,3,5,4],
    "Feed your team-mate(s) the most watermelon": [5,3,3,3,5],
    "List words of a certain length without hesitating": [5,1,4,3,3],
    "The most narcissistic thing": [2,4,3,5,2],
    "Quietly make a cocktail": [2,4,1,5,3],
    "Draw the animal watching you from the mirror": [4,5,1,3,2],
    "Transfer the water from one barrel to another": [4,2,1,5,3],
    "Draw animals using straight lines": [2,4,4,4,2],
    "The best thing that’s bigger at the top than the bottom": [2,3,4,5,1],
    "Move two chickens around a course using a remote-control car and a mobility scooter": [0,4,0,5,3],
    "Communicate the safe contents via reversed audio": [0,3,3,3,0],
    "Make the best and longest-lasting marble run": [4,2,5,0,3],
    "Communicate things to the Taskmaster using only sounds": [5,4,1,3,2],
    "The best thing with wings": [2,1,3,4,5],
    "Fill the cup to overflowing without touching the red green": [0,0,0,0,0],
    "Learn your lines and perform a scene": [3,4,2,2,5],
    "Extract water from a coconut": [0,3,5,0,4],
    "Do not blink while staring at your opponent with a selected expression": [2,4,2,4,4],
    "The best bedding": [3,2,2,4,5],
    "Make the largest beer mat house while ringing the doorbell with increasing frequency": [4,0,0,5,3],
    "Complete the most tasks behind the five motorised doors": [5,3,1,2,4],
    "Work out how many balls are in the basket": [5,0,0,3,4],
    "Draw the monster described by the Taskmaster": [3,4,3,4,5],
    "The greatest collection": [4,3,2,5,1],
    "Put the wellies on the spider’s feet": [5,0,1,4,3],
    "Complete the best performance of a specific song": [5,2,2,2,5],
    "Neatly hang all the clothes on a rail without stepping over the line": [1,4,5,2,3],
    "Balance all the mints or biscuits on a spaghetti bridge": [0,0,0,4,5]
  },
  {
    "The best thing you can carry, but only just": [1,2,4,5,3],
    "Do something impressive under the table while waving": [2,3,3,5,4],
    "Catch the rat": [0,1,5,3,3],
    "Deliver all the plates to Alex": [2,1,5,3,4],
    "Stack your buckets so that they are taller than you": [0,0,0,0,5],
    "The best drinking vessel": [5,1,2,4,3],
    "Make the balloon hover": [0,5,0,4,3],
    "Have an argument": [2,2,5,5,2],
    "Make the house haunted": [3,3,4,4,5],
    "Correctly guess your standing in the group": [2,2,5,4,4],
    "The most shocking cat- to pig-sized thing": [1,3,5,3,3],
    "Make the sauna stones hiss": [4,1,2,3,5],
    "Create a days in month mnemonic": [3,4,1,2,5],
    "Get your luggage through security": [0,0,5,0,4],
    "Act out nursery rhymes": [3,3,5,5,3],
    "The craziest thing": [4,3,1,4,5],
    "Get all of the banana in the bottle": [1,3,4,0,5],
    "Put the bag of salt onto that table": [5,5,0,0,5],
    "Get the sheet of loo roll as far away as possible": [0,5,0,0,4],
    "Identify the contents of the bowl": [3,5,2,2,4],
    "The best thing you can operate with your hand": [1,5,4,3,2],
    "Cover your legs in cling film and gaffer tape / Put on the captain’s hat": [3,5,1,2,4],
    "Make the best uniform for this bee": [4,1,5,3,2],
    "Sort the objects with your face": [5,0,0,4,0],
    "Slap and tong": [4,4,2,2,4],
    "The most annoying thing": [2,5,1,3,4],
    "Make a portrait of the Taskmaster on a door using your feet": [3,5,1,2,4],
    "Vandalise a wall creatively": [1,1,5,5,1],
    "Identify the battered items": [3,5,1,2,4],
    "Tie the string to the glasses and put them on": [2,1,5,4,3],
    "The best thing to hang on a wall that you wouldn’t normally hang on a wall": [4,2,5,1,4],
    "Complete the most tasks": [2,4,3,5,1],
    "Make the best babushka meal": [2,5,4,1,4],
    "Get out of the front gate": [0,0,5,5,0],
    "Make your rubber gloves and wellies as heavy as possible": [1,1,5,2,3],
    "The most satisfying wobbly thing": [3,3,3,3,3],
    "Complete various tasks while saying ‘metronome’": [1,4,4,5,1],
    "Draw the best picture of a British animal": [2,2,3,3,2],
    "Perform the greatest aircraft safety demonstration": [4,4,3,5,3],
    "One leg or two?": [1,3,5,1,3],
    "The nattiest knitwear": [5,3,4,4,2],
    "Make the most impressive weather for Taskmaster Island": [5,2,1,4,3],
    "Build and topple a tower for a pot of yoghurt": [5,3,0,0,4],
    "Appear as different as possible in four photos": [4,2,3,5,3],
    "Shove your fish": [1,3,1,5,4],
    "The thing that makes you look the toughest": [3,4,2,5,1],
    "Make the best picture of a big, scary dinosaur": [2,3,4,1,5],
    "Scientifically work out how much Alex’s feet and head weigh": [4,1,5,2,3],
    "Direct a teammate into the red circle": [2,2,5,5,2],
    "Keeping your head still at all times, correctly don your special outfit": [5,2,3,4,1]
  },
  {
    "The nicest thing to sit on": [4,5,1,2,3],
    "Strike Alex with a ball": [1,4,2,6,3],
    "Paint a flattering picture of the Taskmaster in action": [4,3,5,2,1],
    "Pop the balloon": [5,1,3,2,4],
    "Strike poses to represent a hobby, an animal, and a celebrity": [1,3,3,5,1],
    "The most awesome square": [4,1,5,2,3],
    "Scale the mountain": [3,5,5,5,3],
    "Work out the contents of the bags": [3,4,1,3,5],
    "Paint the space hopper green": [3,2,4,5,1],
    "Put on the medallion": [3,4,5,2,1],
    "The most old-fashioned thing that you still use": [3,5,4,2,1],
    "Copy Alex": [1,4,2,3,5],
    "Make a sand bridge across the river": [6,3,1,5,2],
    "Film a thrilling sequence with a welly-cam": [2,5,3,4,3],
    "Convey objects using shadows": [2,4,4,4,2],
    "The best thing that has quite a few layers": [5,4,3,1,2],
    "Complete the course as slowly as possible": [4,5,3,1,2],
    "Spread jam on toast in a really cool way": [4,2,5,2,3],
    "Solve the riddle": [5,2,2,4,5],
    "Get the most forks in your bucket": [3,2,1,5,4],
    "The most elegant thing beginning with 'G'": [4,1,5,3,2],
    "Sit on a cake": [2,4,3,6,5],
    "Get the most balls in the net": [0,0,0,0,0],
    "Prevent Alex from scoring a goal": [4,1,3,5,2],
    "Pop the most balloons": [4,2,10,3,1],
    "The most desirable thing for another contestant": [2,5,3,4,1],
    "Land the iron on the ironing board": [5,1,4,2,3],
    "Make a cute toy for a cute dog": [3,1,5,4,2],
    "Sit on the red chair in the secret tower": [3,5,2,4,1],
    "Make paper aeroplanes": [1,5,5,3,2],
    "The most ridiculous thin thing": [3,4,1,2,5],
    "Put up a shelf for the Taskmaster's snooker balls": [4,3,3,3,3],
    "Write and perform a 30-second jingle": [4,5,4,5,2],
    "Pass everything through the pipe and the pipe through everything": [0,5,0,4,3],
    "Direct drawings using limited keywords": [5,0,0,0,5],
    "The best thing you have repurposed": [4,5,3,2,1],
    "Make a popcorn necklace and do the right thing": [4,-5,5,3,-5],
    "Play and commentate on a socially-distanced sport": [5,5,5,5,5],
    "Make your face look like another face when it's upside-down": [5,2,4,4,5],
    "Pop up before the objects": [3,2,4,5,3],
    "The best 40 identical things on a towel": [5,4,3,1,2],
    "Have the longest telephone conversation": [1,5,3,2,4],
    "Find the soldier with hindsight": [1,4,3,5,2],
    "Get goosebumps": [4,3,0,5,0],
    "Duck-slide": [0,5,5,5,0],
    "The most magnificent floppy thing": [4,5,4,2,1],
    "Drink with your mouth open": [3,5,4,2,1],
    "Describe the Taskmaster / Chocolate button / Guess the tasks": [5,4,4,4,5],
    "Propose to Alex": [4,4,5,5,3],
    "Make noises without being identified by the Taskmaster": [3,3,5,5,3]
  },
  {
    "The most exciting thing to be found in a skip": [1,5,4,2,3],
    "Find all ten ducks in the lab": [1,3,5,4,3],
    "Create a lipstick portrait of the Taskmaster": [3,4,5,1,3],
    "Duel with Alex": [2,3,4,1,5],
    "Count to 13": [3,1,5,2,4],
    "The object you would most like to show to an alien": [5,2,2,2,2],
    "Tie a ribbon round the maypole or hit it with a ping pong ball": [3,1,4,2,5],
    "Recreate the coolest photo from your phone": [1,5,4,3,2],
    "Score an exercise ball hat-trick using a buggy": [5,3,5,3,3],
    "Draw and describe the object under your table": [1,5,3,4,1],
    "The item that sounds funniest when you say its name over and over again": [3,4,3,5,2],
    "Recreate a historical moment using traffic cones": [4,5,2,1,3],
    "Make all the things happen at the same time": [0,4,5,0,0],
    "Enable Alex to bite his duck": [2,6,1,4,5],
    "Face leg or other leg?": [2,6,2,6,6],
    "The best night-time thing": [5,4,2,1,3],
    "Guess Shoe": [2,1,5,4,3],
    "Give Alex the best stag minute": [5,4,5,4,4],
    "Make a stirring speech out of the bunting": [1,2,4,5,3],
    "Knock over your opponents' dolls with a tyre": [4,5,1,2,3],
    "The most surprising thing from your wardrobe": [4,5,1,3,2],
    "High-five Alex": [4,0,4,0,5],
    "Raise the water level to the top of the fish tank": [5,0,0,4,0],
    "Answer Alex's phone call": [5,1,4,3,2],
    "Pop balls out of your hole": [3,5,2,1,4],
    "The most calming item": [5,1,4,2,3],
    "Use a cement mixer": [1,2,5,3,1],
    "Record a high number on a pedometer": [2,5,4,1,3],
    "Hold a meeting with yourselves": [4,1,2,5,3],
    "Correctly guess the person's first name": [0,0,0,0,5],
    "The nicest thing to put your finger in": [5,3,3,3,4],
    "Show off": [3,2,5,4,5],
    "Deliver a cocktail to Greg": [2,5,2,5,5],
    "Create an edible sculpture": [4,5,5,4,5],
    "Eat your beautiful sculpture": [2,1,3,5,4],
    "Build the tallest tower of toilet rolls": [4,3,1,3,5],
    "The loveliest thing to hold above your head": [1,5,3,2,5],
    "Learn Swedish": [5,4,1,2,3],
    "Poke your tongue out for the longest time": [2,3,4,1,5],
    "Walk through the door wearing the longest shoes and biggest hat": [5,5,1,2,3],
    "Write down things that fit the category": [5,3,5,3,3],
    "The best object with a handle": [5,2,1,4,3],
    "Get the most surprising thing delivered": [2,4,5,4,2],
    "Make the longest cup snake": [2,1,4,5,3],
    "Poke a body part out of the shower curtain": [0,0,5,4,5],
    "Predict how many cans you can fit in a bag": [5,0,4,0,0],
    "The finest family heirloom": [4,5,4,2,4],
    "Identify the liquids": [4,3,4,4,5],
    "Get the most ducks in Alex's basket": [3,0,5,0,4],
    "Record a multi-track song about your team": [3,5,3,5,5],
    "Draw a life-size self portrait with your nose in the canvas": [1,5,5,2,4]
  },
  {
    "The most jaw-dropping item": [4,5,1,2,4],
    "What ten films are you in?": [1,3,2,5,4],
    "Land loo roll in the toilet": [5,4,1,2,3],
    "Create the best picture of a bird": [2,2,2,5,5],
    "Don't pop the balloon": [5,3,5,0,2],
    "The best thing you can't throw away": [5,3,1,4,3],
    "Print, laminate, and distribute the most signs": [5,4,1,2,3],
    "Obey all your signs": [5,2,1,5,3],
    "Put five grapes in the little bowl": [5,0,3,4,2],
    "Sort the ducks and the socks": [7,2,1,4,3],
    "Make the Taskmaster say your words": [3,3,3,2,2],
    "The thing you most want on a Sunday morning": [4,3,5,1,2],
    "Put the most sand in the shopping trolley": [0,0,5,5,5],
    "Identify the ice cream flavours": [5,4,4,1,2],
    "Catch something": [5,4,2,1,3],
    "Play your sounds right": [3,3,4,3,5],
    "The greatest addition to a garden": [4,1,3,2,5],
    "Turn on the bubble machine": [4,3,2,1,5],
    "Get the tarpaulin into one of the containers": [4,3,2,1,5],
    "Write a classic song incorporating five wonderful words": [2,4,4,2,5],
    "Egg and spoon throw": [5,4,1,3,2],
    "The most useless thing that cost over £20": [4,3,5,3,2],
    "Get the most pleasure from these rubber chutes": [2,5,3,4,4],
    "Perform the best routine to this music": [5,5,5,4,4],
    "Luggage trolley bowling": [3,1,5,4,2],
    "Communicate animals by saying letters and doing impressions": [5,5,5,5,5],
    "The best thing you've ever received in the post": [2,1,3,4,5],
    "Hold the milk bottles above the microwaves": [1,2,4,3,5],
    "Reach the end of two lanes in the same amount of time": [2,1,5,4,5],
    "Strike the bullseye with your paint": [0,0,0,0,0],
    "Paint a unicorn using your head brush": [5,2,1,3,4],
    "The thing you'd most like to have on a car journey": [3,4,2,1,5],
    "Pop 99 red balloons": [4,0,5,0,0],
    "Get this feather into the bath": [5,5,5,2,2],
    "Hit Bernard with an exercise ball": [4,2,5,0,3],
    "Blow an item onto The Knappett": [5,5,1,5,5],
    "The best fancy dress": [3,5,1,3,2],
    "Communicate an instruction in a secret language": [0,0,0,5,5],
    "Pin an alluring tail on the alluring animal": [4,1,3,5,2],
    "Find the back of your hand": [0,4,0,5,5],
    "Guess the length of the extendible item": [2,2,2,3,3],
    "The most underestimated item": [3,3,2,1,3],
    "Snort, raspberry, whistle": [3,2,2,5,4],
    "Write a one-minute, one-person play": [4,5,5,1,5],
    "Perform a one-minute, one-person play": [5,5,4,2,3],
    "Paint a self portrait with a selected brush on a selected canvas": [2,5,4,3,1],
    "Get your towel in your bucket": [5,3,2,4,2],
    "The thing the Taskmaster would most like to own": [2,1,3,1,1],
    "Eat the grape": [5,3,1,2,4],
    "Sculpt your team": [3,3,3,5,5],
    "Throw an object, hide an object, and place it on the barrel": [5,1,3,4,2],
    "Land a balloon near the Taskmaster": [5,0,2,4,3]
  },
  {
    "The most dependable thing that weighs about 1kg": [3,1,2,4,5],
    "Have the best first wedding dance with Alex": [1,2,3,5,4],
    "Put a ball of string on the cushion": [1,2,4,3,5],
    "Get all the rubber rings on your bargepole": [2,4,2,3,5],
    "Throw your items into your bucket": [5,0,5,0,0],
    "The object which makes you feel weirdest when you look at it": [4,3,1,5,1],
    "Compose and perform a musical solo": [4,5,5,5,4],
    "Build a bridge over the red green for this potato": [5,5,3,3,3],
    "Achieve an impressive effect with a single breath": [3,1,1,1,4],
    "Create a picture of an animal on the back of your T-shirt": [0,3,5,0,4],
    "The most heroic thing": [3,4,5,1,2],
    "Exit the caravan after exactly 20 minutes": [4,5,3,0,0],
    "Catch the potatoes in the potato hat": [1,2,4,3,5],
    "Perform a slow-motion fight scene": [5,5,4,4,4],
    "Know the most facts about sausages": [3,5,4,1,3],
    "The most fun non-headwear to wear on your head": [5,1,4,3,2],
    "Strike the most drums with a bouncy ball": [4,1,3,2,5],
    "Make the fastest egg boat": [0,3,4,5,2],
    "Task bingo": [3,2,4,3,1],
    "Pour your sand into the other bottle": [0,0,0,0,0],
    "The luckiest thing": [3,3,2,5,4],
    "Fake something": [5,4,2,2,4],
    "Musical Simon Says": [5,2,3,3,5],
    "Salvage the most spoons": [0,0,5,5,5],
    "Stuff your team-mate's waders": [0,0,10,10,10],
    "The best thing to play about with in your bathroom": [5,3,1,4,2],
    "Perform a poignant domestic scene with an imaginary companion": [5,4,2,3,4],
    "Efficiently shell an egg": [1,3,2,4,5],
    "Bash the big bell with the bowling ball": [4,0,0,0,5],
    "Story-time chairs": [3,4,2,1,5],
    "The most brilliant thing that pops up": [5,4,3,2,1],
    "Rotate the pulper wheel without pulping the egg": [4,5,0,3,0],
    "Free yourselves and have a team hug": [2,2,5,5,5],
    "Set the parameters for your own task": [1,1,1,5,4],
    "Imitate accents/walks": [5,2,2,5,5],
    "The thing you take everywhere with you, but struggle to fit in your bag": [4,4,5,4,4],
    "Pile the pineapples on the path": [1,4,3,2,5],
    "Repurpose an umbrella": [3,1,2,5,4],
    "Put the most stuff on top of a jelly": [5,0,1,4,0],
    "Use the scratching post to remove balls from your suit": [3,3,5,5,5],
    "The sneakiest thing": [4,2,4,5,4],
    "Make these things the same colour": [5,5,5,5,5],
    "Deliver a one-minute history lecture": [4,5,2,2,3],
    "Make exactly 99 holes in the piece of paper": [5,0,0,4,0],
    "Estimate the heights of things": [2,4,1,5,3],
    "The best Greg Davies merchandise": [1,4,3,2,5],
    "Fill the glass up to the line": [0,0,4,0,5],
    "Do what Alex does": [5,4,1,2,3],
    "Perform a lullaby for a profession": [4,4,5,5,5],
    "Standing in ice, or not standing in ice?": [0,0,5,0,0]
  },
  {
    "The most wonderful wooden thing you’ve owned for a while": [5,1,3,4,2],
    "Build a tower of cans in the lab": [4,2,5,1,3],
    "Cross the finish line while connected to your team": [5,5,5,2,2],
    "Get the duck into the lake": [0,0,3,4,5],
    "Heavier or lighter?": [5,5,5,2,2],
    "The best sign": [1,2,3,5,4],
    "Pull the sword from the stone": [5,3,2,1,4],
    "Make a cheeky picture using nails and wire": [2,1,5,5,3],
    "Make mischief": [3,2,1,4,5],
    "Draw something you like and something you dislike": [5,2,1,4,3],
    "The present that raises the most questions": [4,3,5,2,1],
    "Get the ball in the hole without touching it": [5,3,4,1,2],
    "Get underneath the most unique things": [4,2,5,4,1],
    "Choose a new nickname": [1,4,5,3,2],
    "Human war boats": [5,5,5,0,0],
    "The best thing for a grown-up that is meant for a child": [4,5,1,3,2],
    "Make a surprisingly pleasant sausage": [4,3,1,5,2],
    "Complete all the tasks as a team": [5,5,5,2,2],
    "Recreate a well-known piece of art on 100 memo squares": [3,1,5,5,3],
    "Roll your animal die": [1,4,5,3,2],
    "The best thing that has five things on it": [4,2,1,3,5],
    "Burst the balloon without looking at it": [3,1,4,5,2],
    "Make a cool but scary googly-eyed gang": [3,1,5,2,4],
    "Get all of the water into the vase": [0,0,0,0,0],
    "Retrieve and sip your drink": [5,3,4,2,2],
    "The greatest thing that makes quite a loud noise when you shake it": [2,4,5,3,1],
    "Avoid the rubbish robots": [1,5,2,3,4],
    "Recreate the garage scene in the lab": [3,3,3,3,3],
    "Present a powerful piece called \"Heads, Shoulders, Knees and Toes\"": [2,5,5,4,4],
    "Pineapple bluff": [1,3,3,4,5],
    "The thing most guaranteed to make you groan": [3,2,2,5,4],
    "Play with these switches / Balance the most golf tees": [0,5,0,0,0],
    "Pie the air dancer in the face": [4,0,3,0,5],
    "Place your cardboard replica within the boundary": [1,4,5,0,1],
    "Get three balls on your hat using litter-pickers": [5,3,4,1,2],
    "The best single-word object you own and love that gets the best reaction when introduced following a drum roll": [4,3,2,5,4],
    "Find the secret task": [0,0,1,-1,0],
    "Complete the fortune trail": [5,0,4,0,3],
    "Convince a child you're asleep": [3,1,5,2,5],
    "Mime the proverbs": [3,3,3,5,5],
    "The bit of old crap that Greg likes the best": [3,1,4,5,2],
    "Drive a sweeper across the finish line": [0,3,2,5,4],
    "Make the best gift for Greg": [4,4,2,5,3],
    "Feed the clown the most cards": [5,0,0,0,0],
    "Answer questions about Alex's parade": [3,1,2,5,5]
  }
];

const episodes = [null, [5,5,6,5,6,5], [5,6,6,6,5], [5,6,6,5,5], [5,6,6,6,6,5,6,6], [5,6,5,7,5,5,6,5], [5,6,5,7,6,6,6,5,6,5], [5,6,5,5,6,6,6,5,6,6], [5,6,5,5,6,6,5,5,6,5], [5,5,6,5,5,5,5,5,5,5], [5,5,5,5,6,5,5,5,5,5], [5,5,5,5,5,5,5,5,5,5], [5,5,5,5,5,5,5,5,5,5], [5,5,5,5,5,5,6,5,5,5], [5,6,5,5,5,5,5,5,6,5], [5,5,5,5,5,5,5,5,5,5], [5,5,5,5,5,5,5,5,5]];

const names = ["Frank Skinner", "Josh Widdicombe", "Roisin Conaty", "Romesh Ranganathan", "Tim Key", "Doc Brown", "Joe Wilkinson", "Jon Richardson", "Katherine Ryan", "Richard Osman", "Al Murray", "Dave Gorman", "Paul Chowdhry", "Rob Beckett", "Sara Pascoe", "Hugh Dennis", "Joe Lycett", "Lolly Adefope", "Mel Giedroyc", "Noel Fielding", "Aisling Bea", "Bob Mortimer", "Mark Watson", "Nish Kumar", "Sally Phillips", "Alice Levine", "Asim Chaudhry", "Liza Tarbuck", "Russell Howard", "Tim Vine", "James Acaster", "Jessica Knappett", "Kerry Godliman", "Phil Wang", "Rhod Gilbert", "Iain Stirling", "Joe Thomas", "Lou Sanders", "Paul Sinha", "Sian Gibson", "David Baddiel", "Ed Gamble", "Jo Brand", "Katy Wix", "Rose Matafeo", "Daisy May Cooper", "Johnny Vegas", "Katherine Parkinson", "Mawaan Rizwan", "Richard Herring", "Charlotte Ritchie", "Jamali Maddix", "Lee Mack", "Mike Wozniak", "Sarah Kendall", "Alan Davies", "Desiree Burch", "Guz Khan", "Morgana Robinson", "Victoria Coren Mitchell", "Ardal O'Hanlon", "Bridget Christie", "Chris Ramsey", "Judi Love", "Sophie Duker", "Dara \u00d3 Briain", "Fern Brady", "John Kearns", "Munya Chawawa", "Sarah Millican", "Frankie Boyle", "Ivo Graham", "Jenny Eclair", "Kiell Smith-Bynoe", "Mae Martin", "Julian Clary", "Lucy Beaumont", "Sam Campbell", "Sue Perkins", "Susan Wokoma"];
